---
title: "psgsrs_19.Rmd"
output: html_document
---

#code to reproduce (hopefully) all graphs displayed during the presentation

CNS length distribution

```{r}
rm(list=ls(all=TRUE))
library(tidyverse)
library(ggplot2)


file.path <- "/insert/full/path/here"
length_df <- read.table( paste0(file.path,"/path_to/CNS_Brassicaceae_at_gene_nodups_mi_ldv.txt"), row.names = NULL)
colnames(length_df) <- "Length"
med_len <- median(length_df$Length)
ldv_graph <- length_df %>%
  ggplot(aes(x=Length)) +
  geom_density() +
  xlim(0,250) +
  geom_vline(xintercept = median(length_df$Length)) +
  geom_text(aes(x=median(length_df$Length), label=paste0("Median length = ",median(length_df$Length)), y=0.05))
ldv_graph
#
png(filename = paste0(file.path,"/CNS_Brassicaceae_at_gene_nodups_mi_ldv.png"), units = "in", res = 400, width = 11, height = 8.5)
  plot(ldv_graph)
  dev.off()

```

Subsampling graph:

```{r}
library(tidyverse)
library(ggplot2)

file.path <- "/path/to/files"
mi_mo_gene_sub <- read.table(file = paste0(file.path,"/mi_mo_gene_sub.txt"),sep = "\t",row.names = NULL, header = T)

colnames(mi_mo_gene_sub)[3] <- "Mean Unique Sequences"

all_line_graph <- mi_mo_gene_sub %>%
  ggplot(aes(x = Ecotypes, y = `Mean Unique Sequences`, colour = Type)) +
  scale_color_manual(values = c("#F8766D", "#00BA38", "#619CFF")) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = `Mean Unique Sequences` -Stdev, ymax=`Mean Unique Sequences`+Stdev),position=position_dodge(0.05)) +
  ylim(0,6000) +
  xlim(0,30) +
  ggtitle(label = "Subsampling Across Ecotypes") +
  theme_minimal()
all_line_graph
#
png(filename = paste0(file.path,"all_subsample_graph.png"), units = "in", height = 4.18, width = 7.42, res = 600)
  plot(all_line_graph)
  dev.off()

#lets only do PAV_Gene, then layer PosV_CNS
library(scales)
show_col(hue_pal()(3))
#red: #F8766D   PAV_Gene
#green: #00BA38 PosV_CNS
#blue: #619CFF  PAV_CNS

gene_line_graph <- mi_mo_gene_sub[mi_mo_gene_sub$Type == "PAV_Gene",] %>%
  ggplot(aes(x = Ecotypes, y = `Mean Unique Sequences`, colour = Type)) +
  scale_color_manual(values = c("#F8766D")) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = `Mean Unique Sequences` -Stdev, ymax=`Mean Unique Sequences`+Stdev),position=position_dodge(0.05)) +
  ylim(0,6000) +
  xlim(0,30) +
  ggtitle(label = "Subsampling Across Ecotypes") +
  theme_minimal()
gene_line_graph
#
png(filename = paste0(file.path,"all_subsample_graph_1.png"), units = "in", height = 4.18, width = 7.42, res = 600)
  plot(gene_line_graph)
  dev.off()

gene_posv_line_graph <- mi_mo_gene_sub[mi_mo_gene_sub$Type != "PAV_CNS" ,] %>%
  ggplot(aes(x = Ecotypes, y = `Mean Unique Sequences`, colour = Type)) +
  scale_color_manual(values = c("#F8766D","#00BA38")) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = `Mean Unique Sequences` -Stdev, ymax=`Mean Unique Sequences`+Stdev),position=position_dodge(0.05)) +
  ylim(0,6000) +
  xlim(0,30) +
  ggtitle(label = "Subsampling Across Ecotypes") +
  theme_minimal()
gene_posv_line_graph
#
png(filename = paste0(file.path,"all_subsample_graph_2.png"), units = "in", height = 4.18, width = 7.42, res = 600)
  plot(gene_posv_line_graph)
  dev.off()

```

model depth graph code
```{r}
#rm(list=ls(all=TRUE))
library(tidyverse)
library(ggplot2)

file.path <- "/path/to/file"
#read in dataframe
cns_model_depth <- read.table(file = paste0(file.path,"/cns_atac_model_depth.txt"), sep = "\t", row.names = NULL,header = T)

#reorder stack
#cns_model_depth$Type_f = factor(cns_model_depth$Type, levels=c('tair10','coll','tair10_missing','moved','ATAC'))

#rename things
colnames(cns_model_depth) <- c("Feature","Coords","Depth","Density","Gene Distance","Type_f")
cns_model_depth$Feature <- gsub("tair10_missing","PAV",cns_model_depth$Feature)
cns_model_depth$Feature <- gsub("tair10","Col-0",cns_model_depth$Feature)
cns_model_depth$Feature <- gsub("coll","Collinear",cns_model_depth$Feature)
cns_model_depth$Feature <- gsub("moved","PosV",cns_model_depth$Feature)

#redo factors
cns_model_depth$Type_f = factor(cns_model_depth$Feature, levels=c('Col-0','Collinear','PAV','PosV','ATAC'))
levels(cns_model_depth$Type_f)

cns_model_depth_graph <- cns_model_depth %>%
  ggplot(aes(x = `Gene Distance`, y = `Density`)) +
  geom_line(aes(colour = Feature))+
  ylim(0,0.00175) +
  xlim(-2000,2000) +
  ggtitle("Feature density relative to the proximate gene") +
  facet_grid(rows = vars(Type_f)) +
  scale_color_discrete(breaks=c('Col-0','Collinear','PAV','PosV','ATAC')) +
  theme_minimal() +
  theme(legend.text=element_text(size=25),
        legend.title = element_text(size = 25),
        axis.text=element_text(size=25),
        axis.title.x = element_text(size=25),
        axis.title.y = element_text(size=25),
        axis.text.y = element_blank(),
        title = element_text(size=25),
        strip.text.y = element_text(size = 20)) 
cns_model_depth_graph
  #cns_model_depth_graph_1500_all <- cns_model_depth_graph
#cns_model_depth_graph_all_0.0015 <- cns_model_depth_graph
#cns_model_depth_graph_2500_0.002 <- cns_model_depth_graph

#savsies
png(filename = paste0(file.path,"06_model_depth/cns_atac_model_depth_graph_stacked.png"), units = "in", res = 600, width = 11, height = 8.5)
  plot(cns_model_depth_graph)
  dev.off()
```

pca plots:

```{r}
library("transformr")
library("gganimate")
#missing to moved
library(ggrepel)

file.path <- "/path_to_file/"
merged_df <- read.table(file = paste0(file.path,"pca_data_table.txt"),sep = "\t",row.names = NULL, header = T)

moved_to_missing <- merged_df[merged_df$Tag == "Missing" | merged_df$Tag == "Moved",]
moved_to_missing$Tag <- gsub("Missing", "PAV", moved_to_missing$Tag) 
moved_to_missing$Tag <- gsub("Moved", "PosV", moved_to_missing$Tag)
moved_to_missing$Accession <- as.character(moved_to_missing$Accession)

#translate to common names
info_table <- read.table(file = paste0(file.path,"/final_gen_eco_cn_id.txt"),sep = "\t",row.names = NULL,header = T)
#easiest way to switch out names....
#i <- 1
cn_vect <- c()

for (i in 1:nrow(moved_to_missing)) {
  srr_split <- unlist(strsplit(moved_to_missing$Accession[i], split = "_"))
  cn_index <- which(grepl(srr_split[1],info_table$SRR))
  common_name <- as.character(info_table$Common_Name[cn_index])
  cn_vect <- c(cn_vect,common_name)
}
moved_to_missing <- cbind(moved_to_missing, cn_vect)

moved_to_missing_plot <- ggplot(moved_to_missing, aes(PC2, PC1)) +
  geom_point(aes(colour = Group), size = 3) +
  theme(legend.text=element_text(size=25),
        legend.title = element_text(size = 25),
        axis.text=element_text(size=25),
        axis.title.x = element_text(size=25),
        axis.title.y = element_text(size=25),
        title = element_text(size=25)) +
  labs(fill="Admixture Group") +
  #theme(legend.text=element_text(size=50)) +
  labs(title="state: {closest_state}") +
  #ggrepel::geom_text_repel(label=moved_to_missing$Accession, point.padding = 2) +
  #ggrepel::geom_text_repel(label=moved_to_missing$cn_vect, box.padding = unit(3, 'lines')) +
  transition_states(Tag)
animate(moved_to_missing_plot, width = 800, height = 450)
#?animate()

anim_save(paste0(file.path,"/moved_to_missing_pca_50.gif"), moved_to_missing_plot, units = "in", width = (7.76*2), height = (5.63*2), res = 100)
dev.off()
```

Normal distribution figure

```{r}
#
library(tidyverse)
library(ggplot2)

file.path <- "/path/to/output"
#make normal distribution dataframe
test_seq <- seq(-5, 5, by = .01)
test_df <- data.frame(X = test_seq,
                      Prob = dnorm(test_seq))
#
test_dist <- test_df %>%
  ggplot(aes(x = X, y = Prob)) +
  geom_point() +
 # theme(axis.title.y = element_blank()) +
  theme_void()
test_dist
#

png(filename = paste0(file.path,"/normal_dist.png"),width = 5.21, height = 2.47, res = 600, units = "in")
  plot(test_dist)
  dev.off()
```

```{r}
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggrepel_0.8.0    gganimate_1.0.2  transformr_0.1.1 ggfortify_0.4.5  scales_0.5.0    
 [6] usethis_1.4.0    devtools_2.0.1   Sushi_1.7.1      biomaRt_2.38.0   zoo_1.8-4       
[11] bindrcpp_0.2.2   forcats_0.3.0    stringr_1.3.1    dplyr_0.7.5      purrr_0.2.5     
[16] readr_1.1.1      tidyr_0.8.1      tibble_1.4.2     ggplot2_3.1.0    tidyverse_1.2.1 

loaded via a namespace (and not attached):
 [1] nlme_3.1-137          bitops_1.0-6          fs_1.2.6              sf_0.7-2             
 [5] lubridate_1.7.4       bit64_0.9-7           progress_1.2.0        httr_1.3.1           
 [9] rprojroot_1.3-2       tools_3.5.0           backports_1.1.2       R6_2.2.2             
[13] splitstackshape_1.4.6 DBI_1.0.0             lazyeval_0.2.1        BiocGenerics_0.26.0  
[17] colorspace_1.3-2      withr_2.1.2           tidyselect_0.2.4      gridExtra_2.3        
[21] prettyunits_1.0.2     mnormt_1.5-5          processx_3.1.0        bit_1.1-14           
[25] curl_3.2              compiler_3.5.0        cli_1.0.0             rvest_0.3.2          
[29] Biobase_2.40.0        xml2_1.2.0            desc_1.2.0            labeling_0.3         
[33] classInt_0.3-1        psych_1.8.4           callr_2.0.4           digest_0.6.15        
[37] foreign_0.8-70        pkgconfig_2.0.1       sessioninfo_1.1.1     rlang_0.2.1          
[41] readxl_1.1.0          rstudioapi_0.7        RSQLite_2.1.1         farver_1.1.0         
[45] bindr_0.1.1           jsonlite_1.5          RCurl_1.95-4.11       magrittr_1.5         
[49] Rcpp_0.12.17          munsell_0.4.3         S4Vectors_0.18.3      stringi_1.2.2        
[53] yaml_2.1.19           pkgbuild_1.0.2        plyr_1.8.4            grid_3.5.0           
[57] blob_1.1.1            parallel_3.5.0        crayon_1.3.4          lattice_0.20-35      
[61] haven_1.1.1           hms_0.4.2             knitr_1.20            pillar_1.2.3         
[65] lpSolve_5.6.13        reshape2_1.4.3        stats4_3.5.0          pkgload_1.0.2        
[69] XML_3.98-1.19         glue_1.2.0            gifski_0.8.6          data.table_1.11.8    
[73] remotes_2.0.2         modelr_0.1.2          png_0.1-7             tweenr_1.0.1         
[77] testthat_2.0.0        cellranger_1.1.0      gtable_0.2.0          assertthat_0.2.0     
[81] broom_0.4.4           e1071_1.7-0           class_7.3-14          AnnotationDbi_1.42.1 
[85] memoise_1.1.0         IRanges_2.14.10       units_0.6-2          
```












  
  
  
